allowBuilds:
  esbuild: true
  vue-demi: true
overrides:
  shell-quote: '>=1.8.5'
  'js-yaml@>=4.0.0': '>=4.1.2'
  brace-expansion: '>=2.1.4'
  js-yaml: '>=5.2.2'
  postcss: '>=8.5.25'
  lodash: '>=4.17.21'
  flatted: '>=3.3.2'
  minimatch: '>=9.0.5'
  rollup: '>=4.22.4'
  '@babel/core': '>=7.26.10'
  picomatch: '>=2.3.1'
  '@intlify/core-base': '>=9.14.5'
  vue-i18n: '>=9.14.5'
